from datetime import datetime

from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Text

from app.core.database import Base


class RiskExplanation(Base):
    """Stores AI-generated explanations for transaction risk scores"""
    __tablename__ = "risk_explanations"

    id = Column(Integer, primary_key=True, index=True)

    transaction_id = Column(
        Integer,
        ForeignKey("transactions.id"),
        nullable=False,
        index=True,
        unique=True,
    )

    # Risk score components
    ml_score = Column(Float, default=0.0, nullable=False)  # Machine learning model score (0-100)
    rules_score = Column(Float, default=0.0, nullable=False)  # Rules engine score (0-100)
    behavior_score = Column(Float, default=0.0, nullable=False)  # Customer behavior score (0-100)

    # Final score and level
    final_risk_score = Column(Float, nullable=False)  # Combined 0-100
    risk_level = Column(String(50), nullable=False)  # LOW, MEDIUM, HIGH

    # Human-readable explanations
    summary = Column(Text, nullable=False)  # Brief summary
    reasons = Column(Text, nullable=False)  # JSON array of reason strings

    # Contributing factors
    ml_factors = Column(Text, nullable=True)  # JSON array from ML model
    rules_factors = Column(Text, nullable=True)  # JSON array from rules engine
    behavior_factors = Column(Text, nullable=True)  # JSON array from behavior analysis

    # Rules that contributed
    triggered_rule_ids = Column(Text, nullable=True)  # JSON array of rule IDs

    # Decision recommendation
    recommended_decision = Column(String(50), nullable=False)  # APPROVE, REVIEW, BLOCK

    # Generated by system/AI
    generated_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )
    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )
